---
title: "Differential Expression Analysis"
author: "Group 39 Amy"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(BiocManager, tidyverse, reshape2, pheatmap, survminer)

# BiocManager::install("DESeq2")
BiocManager::install("maftools")

library(DESeq2)
library(tidyverse)
```

## Reading Data
```{r}
count_matrix <- read_csv(file = "RNAseq_PRAD.csv")
mutation_data <- read_tsv(file = "data_mutations.txt")
patient_data <- read_tsv(file = "data_clinical_patient.txt", skip = 4)
```

## Find Patients with Complete Data
Get Patient ID in Mutation Data
```{r}
mutation_data <- mutation_data |> mutate(PATIENT_ID = substr(Tumor_Sample_Barcode, 1, 12))
```

Get Patient ID's from RNA Data
```{r}
RNA_ColNames <- count_matrix |> colnames() |> substr(1, 12)
sub_intersect <- intersect(patient_data$PATIENT_ID, mutation_data$PATIENT_ID)
main_intersect <- intersect(sub_intersect, RNA_ColNames)
head(main_intersect)
```

```{r}
test_matrix <- count_matrix[,!names(count_matrix) %in% RNA_ColNames]
```

#Mutation Analysis

##1 Visualize mutation summaries
Find patients in mutation data that exists in all data sets.
```{r}
full_data_patient_ids <- intersect(patient_data$PATIENT_ID, mutation_data$PATIENT_ID) |>
intersect(RNA_ColNames)
mutation_intersect <- subset(mutation_data, PATIENT_ID %in% full_data_patient_ids)
patient_intersect <- subset(patient_data, PATIENT_ID %in% full_data_patient_ids)
```

```{r, results='hide'}
library(maftools)
patient_intersect$Tumor_Sample_Barcode <- patient_intersect$PATIENT_ID
laml = read.maf(maf = mutation_intersect, clinicalData = patient_intersect)
```
```{r}
#Writes maf summary to an output file with basename laml.
write.mafSummary(maf = laml, basename = 'laml')
```
```{r}
plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
```
```{r}
#oncoplot for top twenty mutated genes.
oncoplot(maf = laml, top = 20)
```

## Filter Silent and Missense and Regenerate MAF Summary
```{r}
mutation_filtered <- subset(mutation_intersect, Variant_Classification != "Silent")
mutation_filtered <- subset(mutation_filtered, Variant_Classification != "Missense_Mutation")
```


```{r, results='hide'}
laml.fil = read.maf(maf = mutation_filtered, clinicalData = patient_intersect)
write.mafSummary(maf = laml.fil, basename = 'laml_fil')
```


```{r}
plotmafSummary(maf = laml.fil, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
oncoplot(maf = laml, top = 20)
```

```{r}
hugo <- as.data.frame(table(mutation_filtered$Hugo_Symbol))
```
```{r}
##Create the onco matrix
cnv_events = unique(mutation_filtered$Variant_Classification)
oncomat = reshape2::dcast(
  data = mutation_filtered,
  formula = Hugo_Symbol ~ Tumor_Sample_Barcode,
  fun.aggregate = function(x, cnv = cnv_events) {
    x = as.character(x) # >= 2 same/distinct variant classification = Multi_Hit
    xad = x[x %in% cnv]
    xvc = x[!x %in% cnv]
    
    if (length(xvc) > 0) {
      xvc = ifelse(test = length(xvc) > 1,
                   yes = 'Multi_Hit',
                   no = xvc)
    }
    
    x = ifelse(
      test = length(xad) > 0,
      yes = paste(xad, xvc, sep = ';'),
      no = xvc
    )
    x = gsub(pattern = ';$',
             replacement = '',
             x = x)
    x = gsub(pattern = '^;',
             replacement = '',
             x = x)
    return(x)
  },
  value.var = 'Variant_Classification',
  fill = '',
  drop = FALSE
)
```


```{r}
rownames(oncomat) = oncomat$Hugo_Symbol
oncomat <- oncomat[,-1]
oncomat.ordered <- oncomat[order(-hugo$Freq),]
mat <- oncomat.ordered
mat[mat!=""]=1
mat[mat==""]=0
mat <- apply(mat, 2 ,as.numeric)
mat <- as.matrix(mat)
rownames(mat)  <-  row.names(oncomat.ordered)
```

```{r}
reduce.mat <- mat[1:10,]
res <- pheatmap(reduce.mat,
         cluster_rows = F,
         show_colnames=FALSE)
```

## Classify Patients
```{r}
hugo.ordered <- hugo |> arrange(desc(Freq)) |> head(n = 10)

patient.mutation.data <- mutation_data |> 
  select(Tumor_Sample_Barcode, Hugo_Symbol) |>
  filter(Hugo_Symbol %in% pull(select(hugo.ordered, Var1))) |>
  mutate(PATIENT_ID = substr(Tumor_Sample_Barcode, 1, 12)) |>
  select(PATIENT_ID, Hugo_Symbol) |>
  merge(patient_data[, c("PATIENT_ID", "DSS_STATUS","DSS_MONTHS")], by = "PATIENT_ID") |>
  drop_na() |>
  mutate(DSS_STATUS = as.numeric(substr(DSS_STATUS, 1, 1))) |>
  distinct()
```

## Draw Survival Curves
```{r, fig.height = 10}
library(survminer)
library(survival)

sa.plot <- survfit(Surv(DSS_MONTHS, DSS_STATUS) ~  Hugo_Symbol, data = patient.mutation.data)

ggsurvplot(sa.plot,
           pval = T, conf.int = T,
           risk.table = T,
           risk.table.col = "strata",
           linetype = "strata",
           surv.median.line = "hv")
```
```{r}
survdiff(formula = Surv(DSS_MONTHS, DSS_STATUS) ~ Hugo_Symbol, data = patient.mutation.data)
```











